### PR TITLE
Added Keycloak DCR

### PR DESCRIPTION
**Pull request by rewsmith**

### CODE REVIEW

**Comment by davegarvey** [comment]
Thanks. Will review when I'm back from holiday

**Comment by davegarvey** [comment]
@rewsmith I'm getting an issue in the bootstrap not getting on 'ok' response from Keycloak:
```
Fri 18 Feb 2022 04:13:05 UTC Waiting for Keycloak to respond ok
Fri 18 Feb 2022 04:13:05 UTC   Expecting 200 response from http://keycloak:8180/auth/
Fri 18 Feb 2022 04:13:05 UTC     Attempt 1 unsuccessful, received ''
```

I believe it's because I don't have a binding for `keycloak` in my `/etc/hosts` file, as I can access Keycloak ok on `localhost:8180`.

To resolve, you can do one of two things.
1. Add an the `keycloak` hostname to the `tyk_demo_hostnames` array on line 6 of `scripts/common.sh`.
2. Change the hostname to use `localhost` instead.

**Comment by davegarvey** [comment]
I should also say that I think this is a great addition, thanks! 🎉

**Comment by rewsmith** [comment]
Good spot @davegarvey!  I've gone with option (1) and added a `keycloak` hostname to the `tyk_demo_hostnames` array on line 6 of `scripts/common.sh`

**Review by davegarvey — APPROVED** [review]

**Pull request merged**
