### PR TITLE
Add openssl as a requirement to README

### PR DESCRIPTION
**Pull request by letzya**

### CODE REVIEW

**Comment by davegarvey** [comment]
Thanks for the PR Yaara, but I'm not sure that this is required anymore. 

The script used to use the local `openssl` binary, but this ended up causing problems due to the variations that could occur, so it was changed to use the openssl from within the Gateway container.

You can see an example of this [here](https://github.com/TykTechnologies/tyk-demo/blob/32912330b08085a3421fb94aaed9580e03945132/deployments/tyk/bootstrap.sh#L61C11-L61C11), where the `openssl` command is executed within the Gateway container using a `docker exec` command:
```
docker exec -d $(get_service_container_id tyk-gateway) sh -c "openssl req -x509 -newkey rsa:4096 -subj \"/CN=tyk-gateway-2.localhost\" -keyout certs/tls-private-key.pem -out certs/tls-certificate.pem -days 365 -nodes" >>logs/bootstrap.log
```

**Comment by letzya** [comment]
I thought I saw it in the common script, Anyway, it was necessary on the day I opened it since it gave @asoorm an error on hi fresh new tyk-demo installation

**Comment by davegarvey** [comment]
Ok, interesting. Let's keep this open then, to understand what happened
with the error. Thanks

**Comment by davegarvey** [comment]
@asoorm would be good to know more about the issue you faced

**Comment by letzya** [comment]
closing it for now

**Pull request closed without merging**
