### PR TITLE
Update builtin portal catalogue with 2 examples

### PR DESCRIPTION
**Pull request by sedkis**
Replaces current bootstrapped built-in Dev Portal with a single REST API and the UDG version of that API.  Both APIs are open.

### CODE REVIEW

**Comment by davegarvey** [comment]
Looks good. But just wondering why was the Swagger Petstore removed?

**Comment by sedkis** [comment]
@davegarvey 
I suppose it didn't serve any purpose as has been replaced with another OAS REST API to serve as an example

**Comment by davegarvey** [comment]
I think it would be good to reinstate. Reason for this is that it's able to function without an internet connection as we have it running as a container.

One of the things I try to achieve with Tyk Demo is to allow it to function without needing an internet connection. Obviously, this isn't always possible, but it's why I added the httpbin and petstore containers.

**Comment by sedkis** [comment]
Re-added Petstore @davegarvey 👍

**Comment by davegarvey** [comment]
I've noticed an issue with the Petstore Policy/Catalogue. Could be due to drifts between the source JSON objects and the Tyk implementation over time. I'm going to try to reconstruct them as part of this branch.

**Review by davegarvey — APPROVED** [review]

**Pull request merged**
