### PR TITLE
Update New Portal to 1.2.0

### PR DESCRIPTION
**Pull request by JRWu**
Updating New Portal to 1.2.0.
Updating assets to reflect new schema.

### CODE REVIEW

**Review by sedkis — APPROVED** [review]
Works - tested a generic flow checking out a product, all is good!

**Comment by LLe27** [comment]
Works on my end too. Was able to easily deploy and test API consumer workflow.

**Review by zalbiraw — APPROVED** [review]
LGTM

**Comment by zalbiraw** [comment]
Probably should get the tests working?

**Pull request merged**
