### PR TITLE
Moved echo to get the pull command

### PR DESCRIPTION
**Pull request by letzya**
To get the full command printed

### CODE REVIEW

**Comment by letzya** [comment]
My thought behind it: 
I want the command to run `docker-compose ps` or `docker-compose restart SERVICE-NAME` . Since our directory setup is somewhat convoluted it's easier if we show the user what we are actually running. It can't be magic all the way.

**Comment by davegarvey** [comment]
I agree that it's good to print the command. But wouldn't it be better to keep it on line 64, so that it is printed before the error check? Otherwise, if it's moved to line 71 it won't be printed if an error occurs.

**Comment by letzya** [comment]
currently, the output is not enough to run `docker-compose ps`

**Comment by letzya** [comment]
@davegarvey have moved it. can you please check.

**Pull request merged**
