### PR TITLE
data-dog example with mangomm/go-bench-suite

### PR DESCRIPTION
**Pull request by letzya**
Created  newdatadog and bench demos under deployment.

Tests passed
image

### CODE REVIEW

**Comment by davegarvey** [comment]
Thanks for this Yaara. 

Where should I be able to see the analytics data in Datadog?

**Comment by letzya** [comment]
In the dashboard section and in the logs section. I can attach a screenshot.

**Comment by davegarvey** [comment]
Would be very useful to see a screenshot. At the moment I can see things like the container logs, but I can't seem to find the analytics data.

**Comment by letzya** [comment]
That's odd. In the dashboard did you try to create a new widget and type "pump" in the search? They are called pump.request_time.something. Have you set all the env cars?

**Comment by davegarvey** [comment]
I hadn't tried that, so I just did and it didn't seem to find anything

image

**Comment by davegarvey** [comment]
I set the env vars by copy/pasting from the readme and replacing the api key, using the one from my datadog dashboard.

The agent is sending data, as I can see things like the CPU usage.

**Review by davegarvey — APPROVED** [review]

**Pull request merged**
